### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 202552: character maps to <undefined>

### ISSUE THREAD

**Issue by Pittsie72** [Nllii/jobfilter#1]
Hi, 

I found your code when looking into JobFunnel and it sounds as though that project is being abandoned, I downloaded your code and attempted to run but got the following:
```
python .\jobfilter.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1007k    0 1007k    0     0   883k      0 --:--:--  0:00:01 --:--:--  884k
Traceback (most recent call last):
  File "C:\Users\Spitt\Documents\Python Scripts\jobfilter-main\jobfilter.py", line 82, in <module>
    start_Job_Search()
  File "C:\Users\Spitt\Documents\Python Scripts\jobfilter-main\jobfilter.py", line 75, in start_Job_Search
    glassdoor.glassdoor_api(keyword= 'Human Resource')
  File "C:\Users\Spitt\Documents\Python Scripts\jobfilter-main\job_apis\glassdoor.py", line 63, in glassdoor_api
    soup = bs4.BeautifulSoup(fp, "html.parser")
  File "C:\Users\Spitt\anaconda3\lib\site-packages\bs4\__init__.py", line 311, in __init__
    markup = markup.read()
  File "C:\Users\Spitt\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 202552: character maps to <undefined>
```

**Comment by Nllii** [comment]
ummm... the traceback is from a function i didn't write :( . 

...can you try running the script  on http://kaggle.com or https://colab.research.google.com 
This is similar to the linux kernel and similar to my mac os.

**Comment by Pittsie72** [comment]
That's what I thought but wanted to make sure before I dug into it. Any good way to use either of those?
